#ifndef RPCRUNTIMEFUNCTION_H
#define RPCRUNTIMEFUNCTION_H

#include "rpcruntime_paramter_description.h"

class RPCRuntimeDecodedFunctionCall;

#include <functional>
#include <string>
#include <vector>

/*
 * A RPCRuntimeFunction describes a function generated by the RPC-Generator.
 */

//maybe we will need to differentiate between request and reply functions
class RPCRuntimeFunction {
	public:
	RPCRuntimeFunction(int request_id, int reply_id, std::vector<RPCRuntimeParameterDescription> request_parameters,
					   std::vector<RPCRuntimeParameterDescription> reply_parameters, std::string function_name, std::string function_declaration);
	const std::string &get_function_name() const;
	const std::string &get_function_declaration() const;

	int get_request_id() const;
	int get_reply_id() const;
	const std::vector<RPCRuntimeParameterDescription> &get_request_parameters() const;
	const std::vector<RPCRuntimeParameterDescription> &get_reply_parameters() const;
	const RPCRuntimeParameterDescription &get_reply_parameter(const std::string &name) const;
	int get_request_size() const;
	int get_reply_size() const;

	private:
	int request_id;
	int reply_id;
	std::vector<RPCRuntimeParameterDescription> request_parameters;
	std::vector<RPCRuntimeParameterDescription> reply_parameters;
	std::string function_name;
	std::string function_declaration;
};

#endif // RPCRUNTIMEFUNCTION_H
