/* This file has been automatically generated by RPC-Generator
   https://github.com/Crystal-Photonics/RPC-Generator
   You should not modify this file manually. */

#ifndef RPC_TRANSMISSION_TYPES_H
#define RPC_TRANSMISSION_TYPES_H

#include <stddef.h>

typedef enum{
        RPC_TRANSMISSION_SUCCESS,
        RPC_TRANSMISSION_FAILURE,
        RPC_TRANSMISSION_COMMAND_UNKNOWN,
        RPC_TRANSMISSION_COMMAND_INCOMPLETE
    } RPC_TRANSMISSION_RESULT;
    
typedef struct {
	RPC_TRANSMISSION_RESULT result;
	size_t size;
} RPC_TRANSMISSION_SIZE_RESULT;

typedef enum {
    RPC_TRANSMISSION_mutex_parsing_complete,
    RPC_TRANSMISSION_mutex_caller,
    RPC_TRANSMISSION_mutex_in_caller,
    RPC_TRANSMISSION_mutex_answer,
    RPC_TRANSMISSION_MUTEX_COUNT
} RPC_TRANSMISSION_mutex_id;
#define RPC_TRANSMISSION_number_of_mutexes 4

#endif /* RPC_TRANSMISSION_TYPES_H */
